Homepage
international-child-art-foundation/arts-olympiad pull request #10
Opened 2023-07-14 06:56 UTC by RuochenRockyWang

Create the homepage and adjust layout for mobile view

2023-07-14 18:04 UTC, Isaac-Best approved these changes
Looks good

2023-07-15 18:31 UTC, Andrew-Dame requested changes

2023-07-15 18:31 UTC, Andrew-Dame commented on src/app/page.tsx
> +          alt="banner-image.png"
Please adjust all alternative text on this page to be more descriptive. 

For more info regarding accessible descriptions, please see https://accessibility.huit.harvard.edu/describe-content-images

2023-07-16 00:42 UTC, Andrew-Dame requested changes

2023-07-16 00:42 UTC, Andrew-Dame commented on src/app/page.tsx
> +          alt="bars making a smooth 90 degree curve in olympic colors"
Thanks for adding these alt texts. Two requests: 
 
 - Please capitalize the first letter of the first word of each sentence (this text will be visible if the image fails to load).
 - Avoid making references to gender. Simply saying "a person" is enough to get the point across without making any assumptions.

2023-07-19 16:48 UTC, Andrew-Dame approved these changes

2023-07-19 17:45 UTC, merged