Gallery 02
international-child-art-foundation/arts-olympiad pull request #28
Opened 2023-07-22 20:33 UTC by Isaac-Best

Gallery page, artwork page, mock data, artwork photos 
 
- Gallery page uses query parameters, default sort is most recent  
--- I removed the redundant code with the nested dynamic page however I couldn't get the pre-rendering with[ getStaticProps()](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props) to work at all so I had to simplify the logic quite a bit to get it to run the same with query parameters instead of routing parameters
--- sort by most votes is currently not implemented -> I do not know if its something we want /care for as the gallery will have to be re-written anyway **(just let me know if its a feature we want, I can add another client side query)**

- artwork page, lots of hard coding
--- if the artwork is too small I can mess around with tailwind some more to scale it up, or convert the images to svg's and size it up more naturally 

- the reason this is branched from gallery-01 
--- I had to delete some unused files for GitHub action to build properly, but I would like to keep them for later in phase 2 when we use some of nextJS pre-rendering features without digging in commit histories

2023-07-23 18:29 UTC, Andrew-Dame requested changes

2023-07-23 18:29 UTC, Andrew-Dame commented on src/app/gallery/page.tsx
> +          <Image src={gallery_image} alt="Previous artwork submission" />
I'm not sure what this alt description means...could you make this a bit more clear?

2023-07-23 18:29 UTC, Andrew-Dame commented on src/app/gallery/page.tsx
> +// eslint-disable-next-line
Please make these comments more specific. `// eslint-disable-next-line react-hooks/rules-of-hooks` should work

2023-07-23 18:29 UTC, Andrew-Dame commented on src/app/artwork/[artworkId]/page.tsx
> +function getArtworkById(id:string) {
I don't see a need for the `artworks` variable here or `getArtworkById`.

If you import artworks, you can just grab the desired artwork with `find`:

```
import { artworks } from "../../../../mock/artworks";

...

const artwork = artworks.find(artwork => artwork.id === Number(id));
```

I see the potential optimization using modulus here; however, I don't think the gain is enough for the cost of space and increased complexity of adding an additional artworks array.

2023-07-23 18:29 UTC, Andrew-Dame commented on components/pagination/Pagination.tsx
> +  itemsPerPage?: number
Maybe don't make this an optional prop? There isn't much of an interface for this component, and `itemsPerPage` is a core configuration of this component in general.

2023-07-23 18:30 UTC, Andrew-Dame commented
Could we improve the name of this PR please? Something just a bit more descriptive

2023-07-24 20:24 UTC, Isaac-Best commented on components/ArtworkCard.tsx
> +      {/* <p className="font-medium md:font-semi-bold text-lg">id: {id} </p> */}
For clarification you mean line 15 the commented out line only correct?

2023-07-27 01:51 UTC, Andrew-Dame approved these changes

2023-07-27 02:00 UTC, merged