fix: add proper HTML element to home and purpose page
international-child-art-foundation/arts-olympiad pull request #29
Opened 2023-07-23 09:39 UTC by RuochenRockyWang

Add proper HTML element heading and subheading element to home and purpose page

2023-07-23 16:02 UTC, Andrew-Dame requested changes

2023-07-23 16:02 UTC, Andrew-Dame commented on src/app/page.tsx
> +          <h1 className="break-words font-semibold text-4xl pl-6 pt-2">
There should only ever be one `h1` tag for a given page, per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page). 

The idea is that `h1` should effectively communicate the content of the entire page.

2023-07-26 18:49 UTC, Isaac-Best approved these changes
Looks good, there is only one h1 tag per page now.

2023-07-27 01:42 UTC, Andrew-Dame approved these changes

2023-07-27 19:34 UTC, merged